[package]
name = "converse-derive"
version = "0.1.0"
authors = ["spowell <spowell>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
serde = "1.0"
serde_cbor = "0.9"
proc-macro2 = "0.4"

[dependencies.syn]
version = "0.15.24"
features = ["full","derive"]
